import { Restaurant, MenuItem, Order, Category } from "../types/models";

export const RESTAURANTS: Restaurant[] = [
  {
    id: "1",
    name: "Burger Palace",
    cuisine: "American",
    rating: 4.7,
    deliveryTime: "20-30 min",
    deliveryFee: 1.99,
    priceRange: "$$",
    image: require("../../assets/images/Restaurant/Burger_Palace.png"),
    tag: "Popular",
    tagColor: "#FF6B35",
    minOrder: 10.0,
  },
  {
    id: "2",
    name: "Sakura Sushi",
    cuisine: "Japanese",
    rating: 4.9,
    deliveryTime: "30-45 min",
    deliveryFee: 2.49,
    priceRange: "$$$",
    image: require("../../assets/images/Restaurant/Sakura_Sushi.png"),
    tag: "Top Rated",
    tagColor: "#7C3AED",
    minOrder: 15.0,
  },
  {
    id: "3",
    name: "Pizza Piazza",
    cuisine: "Italian",
    rating: 4.5,
    deliveryTime: "25-35 min",
    deliveryFee: 0.99,
    priceRange: "$$",
    image: require("../../assets/images/Restaurant/Pizza_Piazza.png"),
    tag: "Free Delivery",
    tagColor: "#059669",
    minOrder: 12.0,
  },
  {
    id: "4",
    name: "Spice Route",
    cuisine: "Indian",
    rating: 4.6,
    deliveryTime: "35-50 min",
    deliveryFee: 1.49,
    priceRange: "$$",
    image: require("../../assets/images/Restaurant/Spice_Route.png"),
    tag: "New",
    tagColor: "#D97706",
    minOrder: 10.0,
  },
  {
    id: "5",
    name: "Taco Loco",
    cuisine: "Mexican",
    rating: 4.4,
    deliveryTime: "15-25 min",
    deliveryFee: 1.99,
    priceRange: "$",
    image: require("../../assets/images/Restaurant/Taco_Loco.png"),
    tag: "Fast",
    tagColor: "#DC2626",
    minOrder: 8.0,
  },
  {
    id: "6",
    name: "Dragon Noodles",
    cuisine: "Chinese",
    rating: 4.3,
    deliveryTime: "25-40 min",
    deliveryFee: 1.99,
    priceRange: "$$",
    image: require("../../assets/images/Restaurant/Dragon_Noodles.png"),
    tag: "Trending",
    tagColor: "#2563EB",
    minOrder: 10.0,
  },
];

export const MENU_ITEMS: Record<string, MenuItem[]> = {
  "1": [
    {
      id: "m1",
      name: "Classic Smash Burger",
      price: 13.99,
      description:
        "Double smashed patty, American cheese, pickles, special sauce",
      category: "Burgers",
      emoji: "🍔",
    },
    {
      id: "m2",
      name: "BBQ Bacon Burger",
      price: 15.99,
      description: "Smoky BBQ, crispy bacon, cheddar, caramelized onions",
      category: "Burgers",
      emoji: "🥓",
    },
    {
      id: "m3",
      name: "Crispy Chicken Sandwich",
      price: 12.99,
      description: "Buttermilk fried chicken, coleslaw, pickled jalapeños",
      category: "Sandwiches",
      emoji: "🍗",
    },
    {
      id: "m4",
      name: "Loaded Fries",
      price: 8.99,
      description: "Crispy fries with cheese sauce, bacon bits, scallions",
      category: "Sides",
      emoji: "🍟",
    },
    {
      id: "m5",
      name: "Onion Rings",
      price: 6.99,
      description: "Beer-battered thick-cut onion rings",
      category: "Sides",
      emoji: "🧅",
    },
    {
      id: "m6",
      name: "Chocolate Shake",
      price: 5.99,
      description: "Thick hand-spun chocolate milkshake",
      category: "Drinks",
      emoji: "🥤",
    },
  ],
  "2": [
    {
      id: "m7",
      name: "Salmon Nigiri (2pc)",
      price: 9.99,
      description: "Fresh Atlantic salmon over seasoned sushi rice",
      category: "Nigiri",
      emoji: "🍣",
    },
    {
      id: "m8",
      name: "Dragon Roll",
      price: 16.99,
      description: "Shrimp tempura, cucumber, avocado, eel sauce",
      category: "Rolls",
      emoji: "🐉",
    },
    {
      id: "m9",
      name: "Spicy Tuna Roll",
      price: 14.99,
      description: "Fresh tuna, sriracha mayo, cucumber",
      category: "Rolls",
      emoji: "🌶️",
    },
    {
      id: "m10",
      name: "Miso Soup",
      price: 3.99,
      description: "Traditional dashi, tofu, wakame, scallions",
      category: "Starters",
      emoji: "🫕",
    },
    {
      id: "m11",
      name: "Edamame",
      price: 4.99,
      description: "Steamed salted edamame pods",
      category: "Starters",
      emoji: "🫘",
    },
    {
      id: "m12",
      name: "Matcha Ice Cream",
      price: 5.99,
      description: "House-made ceremonial grade matcha gelato",
      category: "Desserts",
      emoji: "🍵",
    },
  ],
  "3": [
    {
      id: "m13",
      name: "Margherita",
      price: 14.99,
      description: "San Marzano tomato, fresh mozzarella, basil, EVO",
      category: "Pizzas",
      emoji: "🍕",
    },
    {
      id: "m14",
      name: "Pepperoni Feast",
      price: 17.99,
      description: "Double layer pepperoni, mozzarella, tomato",
      category: "Pizzas",
      emoji: "🫕",
    },
    {
      id: "m15",
      name: "Truffle Mushroom",
      price: 19.99,
      description: "White truffle oil, mixed mushrooms, parmesan, arugula",
      category: "Pizzas",
      emoji: "🍄",
    },
    {
      id: "m16",
      name: "Caesar Salad",
      price: 9.99,
      description: "Romaine, parmesan, house-made dressing, croutons",
      category: "Salads",
      emoji: "🥗",
    },
    {
      id: "m17",
      name: "Garlic Bread",
      price: 5.99,
      description: "Toasted sourdough, herb butter, garlic confit",
      category: "Sides",
      emoji: "🥖",
    },
    {
      id: "m18",
      name: "Tiramisu",
      price: 7.99,
      description: "Classic Italian, ladyfingers, espresso, mascarpone",
      category: "Desserts",
      emoji: "☕",
    },
  ],
  "4": [
    {
      id: "m19",
      name: "Butter Chicken",
      price: 16.99,
      description: "Tandoor-roasted chicken in rich tomato cream sauce",
      category: "Mains",
      emoji: "🍛",
    },
    {
      id: "m20",
      name: "Lamb Biryani",
      price: 18.99,
      description: "Slow-cooked basmati, tender lamb, saffron, fried onion",
      category: "Mains",
      emoji: "🍚",
    },
    {
      id: "m21",
      name: "Paneer Tikka",
      price: 13.99,
      description: "Marinated cottage cheese, bell peppers, onion",
      category: "Starters",
      emoji: "🧀",
    },
    {
      id: "m22",
      name: "Dal Makhani",
      price: 11.99,
      description: "Black lentils simmered overnight in tomato cream",
      category: "Mains",
      emoji: "🫘",
    },
    {
      id: "m23",
      name: "Garlic Naan",
      price: 3.49,
      description: "Tandoor-baked with garlic, butter, cilantro",
      category: "Breads",
      emoji: "🫓",
    },
    {
      id: "m24",
      name: "Mango Lassi",
      price: 4.99,
      description: "Fresh Alphonso mango, yogurt, cardamom",
      category: "Drinks",
      emoji: "🥭",
    },
  ],
  "5": [
    {
      id: "m25",
      name: "Street Tacos (3pc)",
      price: 11.99,
      description: "Carne asada, white onion, cilantro, salsa verde",
      category: "Tacos",
      emoji: "🌮",
    },
    {
      id: "m26",
      name: "Fish Tacos (3pc)",
      price: 13.99,
      description: "Baja-style battered fish, chipotle slaw, pico",
      category: "Tacos",
      emoji: "🐟",
    },
    {
      id: "m27",
      name: "Carne Asada Burrito",
      price: 14.99,
      description: "Grilled steak, rice, black beans, cheese, guac",
      category: "Burritos",
      emoji: "🌯",
    },
    {
      id: "m28",
      name: "Nachos Supreme",
      price: 12.99,
      description: "Tortilla chips, queso, jalapeños, sour cream, guac",
      category: "Snacks",
      emoji: "🫔",
    },
    {
      id: "m29",
      name: "Elote",
      price: 5.99,
      description: "Grilled corn, cotija, chili-lime mayo, cilantro",
      category: "Sides",
      emoji: "🌽",
    },
    {
      id: "m30",
      name: "Horchata",
      price: 3.99,
      description: "Traditional rice milk with cinnamon and vanilla",
      category: "Drinks",
      emoji: "🥛",
    },
  ],
  "6": [
    {
      id: "m31",
      name: "Dan Dan Noodles",
      price: 13.99,
      description: "Sesame-chili broth, minced pork, bok choy, peanuts",
      category: "Noodles",
      emoji: "🍜",
    },
    {
      id: "m32",
      name: "Kung Pao Chicken",
      price: 14.99,
      description: "Wok-fried chicken, peanuts, dried chili, scallions",
      category: "Mains",
      emoji: "🍗",
    },
    {
      id: "m33",
      name: "Xiaolongbao (6pc)",
      price: 11.99,
      description: "Soup dumplings, pork, ginger, scallion",
      category: "Dumplings",
      emoji: "🥟",
    },
    {
      id: "m34",
      name: "Spring Rolls (4pc)",
      price: 7.99,
      description: "Crispy vegetable spring rolls with sweet chili dip",
      category: "Starters",
      emoji: "🥢",
    },
    {
      id: "m35",
      name: "Fried Rice",
      price: 10.99,
      description: "Wok-fried jasmine rice, egg, vegetables, soy",
      category: "Rice",
      emoji: "🍚",
    },
    {
      id: "m36",
      name: "Bubble Tea",
      price: 5.99,
      description: "Milk tea with tapioca pearls, choose your sweetness",
      category: "Drinks",
      emoji: "🧋",
    },
  ],
};

export const CATEGORIES: Category[] = [
  { id: "all", label: "All", emoji: "🍽️" },
  { id: "burgers", label: "Burgers", emoji: "🍔" },
  { id: "sushi", label: "Sushi", emoji: "🍣" },
  { id: "pizza", label: "Pizza", emoji: "🍕" },
  { id: "indian", label: "Indian", emoji: "🍛" },
  { id: "mexican", label: "Mexican", emoji: "🌮" },
  { id: "chinese", label: "Chinese", emoji: "🍜" },
];

export const PAST_ORDERS: Order[] = [
  {
    id: "o1",
    restaurantName: "Burger Palace",
    emoji: "🍔",
    items: ["Classic Smash Burger", "Loaded Fries"],
    total: 22.98,
    date: "2 days ago",
    status: "Delivered",
  },
  {
    id: "o2",
    restaurantName: "Sakura Sushi",
    emoji: "🍱",
    items: ["Dragon Roll", "Miso Soup", "Edamame"],
    total: 24.97,
    date: "5 days ago",
    status: "Delivered",
  },
  {
    id: "o3",
    restaurantName: "Pizza Piazza",
    emoji: "🍕",
    items: ["Margherita", "Garlic Bread"],
    total: 20.98,
    date: "1 week ago",
    status: "Delivered",
  },
];
